ShopApp.WebUI/Controllers/CartController.cs
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShopApp.Business.Abstratc;
using ShopApp.Business.Models.VMs.CartVms;
using ShopApp.Business.Models.VMs.OrderVms;
using ShopApp.DataAccess.Identity;
using ShopApp.Entity.Entities;
using ShopApp.Entity.Enums;

namespace ShopApp.WebUI.Controllers;

public class CartController : Controller
{
    //private ICartService _cartService;
    //private IOrderService _orderService;
    //private UserManager<User> _userManager;
    //public CartController(ICartService cartService, IOrderService orderService, UserManager<User> userManager)
    //{
    //    _cartService = cartService;
    //    _orderService = orderService;
    //    _userManager = userManager;
    //}
    //public IActionResult Index(string userId)
    //{
    //    var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
    //    var model = new CartModel()
    //    {
    //        CartId = cart.Id,
    //        CartItems = cart.CartItems.Select(i => new CartItemModel()
    //        {
    //            CartItemId = i.CartId,
    //            ProductId = i.ProductId,
    //            Name = i.Product.Name,
    //            Price = (double)i.Product.Price,
    //            ImageUrl = i.Product.ImageUrl,
    //            Quantity = i.Quantity
    //        }).ToList()
    //    };
    //    return View(model);
    //}

    //public IActionResult AddToCart()
    //{
    //    return View();
    //}
    //[HttpPost]
    //public IActionResult AddToCart(int productId, int quantity)
    //{
    //    var userId = _userManager.GetUserId(User);
    //    _cartService.AddToCart(userId, productId, quantity);
    //    return RedirectToAction("Index");
    //}
    //[HttpPost]
    //public IActionResult DeleteFromCart(int productId)
    //{
    //    var userId = _userManager.GetUserId(User);
    //    _cartService.DeleteFromCart(userId, productId);
    //    return RedirectToAction("Index");
    //}

    //public IActionResult Checkout()
    //{
    //    var orderModel = new OrderModel();
    //    var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
    //    orderModel.CartModel = new CartModel()
    //    {
    //        CartId = cart.Id,
    //        CartItems = cart.CartItems.Select(i => new CartItemModel()
    //        {
    //            CartItemId = i.CartId,
    //            ProductId = i.ProductId,
    //            Name = i.Product.Name,
    //            Price = (double)i.Product.Price,
    //            ImageUrl = i.Product.ImageUrl,
    //            Quantity = i.Quantity
    //        }).ToList()
    //    };
    //    return View(orderModel);
    //}


    //[HttpPost]
    //public IActionResult Checkout(OrderModel model)
    //{
    //        var userId = _userManager.GetUserId(User);
    //        var cart = _cartService.GetCartByUserId(userId);
    //        model.CartModel = new CartModel()
    //        {
    //            CartId = cart.Id,
    //            CartItems = cart.CartItems.Select(i => new CartItemModel()
    //            {
    //                CartItemId = i.CartId,
    //                ProductId = i.ProductId,
    //                Name = i.Product.Name,
    //                Price = (double)i.Product.Price,
    //                ImageUrl = i.Product.ImageUrl,
    //                Quantity = i.Quantity
    //            }).ToList()
    //        };
    //        var payment = PaymentProcess(model);

    //            SaveOrder(model, payment, userId);
    //            ClearCart(model.CartModel.CartId);
    //        //if (payment.Result.Status == "success")
    //        //{
    //        //    return View("Success");
    //        //}
    //        //else {
    //        //    TempData.Put("message", new AlertMessage()
    //        //    {
    //        //        Title = "Payment Error",
    //        //        Message = payment.Result.ErrorMessage,
    //        //        AlertType = "danger"
    //        //    });
    //        //}

    //    return View(model);
    //}

    //private void ClearCart(int cartId)
    //{
    //    _cartService.ClearCart(cartId);
    //}

    //private void SaveOrder(OrderModel model, Task<Payment> payment, string? userId)
    //{
    //    var order = new Order()
    //    {
    //        OrderNumber = (new Random()).Next(111111, 999999).ToString(),
    //        OrderState = OrderState.Completed,
    //        PaymentType = PaymentType.CreditCart,
    //        PaymentId = (new Random()).Next(1111, 9999).ToString(),
    //        ConversationId = (new Random()).Next(111,999).ToString(),
    //        //PaymentId = payment.Result.PaymentId,
    //        //ConversationId = payment.Result.ConversationId,
    //        FirstName = model.FirstName,
    //        LastName = model.LastName,
    //        UserId = userId,
    //        Email = model.Email,
    //        Address = model.Address,
    //        City = model.City,
    //        Phone = model.Phone,
    //        OrderDate = DateTime.Now,
    //        Note = model.Note,
    //        OrderItems = model.CartModel.CartItems.Select(i => new ShopApp.Entity.Entities.OrderItem()
    //        {
    //            Price = i.Price,
    //            Quantity = i.Quantity,
    //            ProductId = i.ProductId
    //        }).ToList()
    //    };
    //    _orderService.Create(order);
    //}

    //private async Task<Payment> PaymentProcess(OrderModel model)
    //{
    //    Options options = new Options();
    //    options.ApiKey = "your api key";
    //    options.SecretKey = "your secret key";
    //    options.BaseUrl = "https://sandbox-api.iyzipay.com";

    //    CreatePaymentRequest request = new CreatePaymentRequest();
    //    request.Locale = Locale.TR.ToString();
    //    request.ConversationId = new Random().Next(111111111, 999999999).ToString();
    //    request.Price = model.CartModel.TotalPrice().ToString();
    //    request.PaidPrice = model.CartModel.TotalPrice().ToString(); ;
    //    request.Currency = Currency.TRY.ToString();
    //    request.Installment = 1;
    //    request.BasketId = "B67832";
    //    request.PaymentChannel = PaymentChannel.WEB.ToString();
    //    request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

    //    PaymentCard paymentCard = new PaymentCard();
    //    paymentCard.CardHolderName = model.CardName;
    //    paymentCard.CardNumber = model.CardNumber;
    //    paymentCard.ExpireMonth = model.ExpirationMonth;
    //    paymentCard.ExpireYear = model.ExpirationYear;
    //    paymentCard.Cvc = model.Cvc;
    //    paymentCard.RegisterCard = 0;
    //    request.PaymentCard = paymentCard;

    //    Buyer buyer = new Buyer();
    //    buyer.Id = "BY789";
    //    buyer.Name = model.FirstName;
    //    buyer.Surname = model.LastName;
    //    buyer.GsmNumber = model.Phone;
    //    buyer.Email = model.Email;
    //    buyer.IdentityNumber = "74300864791";
    //    buyer.LastLoginDate = "2015-10-05 12:43:35";
    //    buyer.RegistrationDate = "2013-04-21 15:12:09";
    //    buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
    //    buyer.Ip = "85.34.78.112";
    //    buyer.City = "Istanbul";
    //    buyer.Country = "Turkey";
    //    buyer.ZipCode = "34732";
    //    request.Buyer = buyer;

    //    Address shippingAddress = new Address();
    //    shippingAddress.ContactName = "Jane Doe";
    //    shippingAddress.City = "Istanbul";
    //    shippingAddress.Country = "Turkey";
    //    shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
    //    shippingAddress.ZipCode = "34742";
    //    request.ShippingAddress = shippingAddress;

    //    Address billingAddress = new Address();
    //    billingAddress.ContactName = "Jane Doe";
    //    billingAddress.City = "Istanbul";
    //    billingAddress.Country = "Turkey";
    //    billingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
    //    billingAddress.ZipCode = "34742";
    //    request.BillingAddress = billingAddress;

    //    List<BasketItem> basketItems = new List<BasketItem>();
    //    BasketItem basketItem;
    //    foreach (var item in model.CartModel.CartItems)
    //    {
    //        basketItem = new BasketItem();
    //        basketItem.Id = item.ProductId.ToString();
    //        basketItem.Name = item.Name;
    //        basketItem.Category1 = "Collectibles";
    //        basketItem.Category2 = "Accessories";
    //        basketItem.Price = item.Price.ToString();
    //        basketItem.ItemType = BasketItemType.PHYSICAL.ToString();


    //        basketItems.Add(basketItem);
    //    }

    //    //BasketItem firstBasketItem = new BasketItem();
    //    //firstBasketItem.Id = "BI101";
    //    //firstBasketItem.Name = "Binocular";
    //    //firstBasketItem.Category1 = "Collectibles";
    //    //firstBasketItem.Category2 = "Accessories";
    //    //firstBasketItem.ItemType = BasketItemType.PHYSICAL.ToString();
    //    //firstBasketItem.Price = "0.3";
    //    //basketItems.Add(firstBasketItem);



    //    return await Payment.Create(request, options);
    //}

}

ShopApp.WebUI/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Newtonsoft.Json;
using ShopApp.Business.Abstratc;
using ShopApp.Business.Models.VMs.ProductVms;
using ShopApp.Entity.Entities;
using System;
using System.Net;
using System.Net.Http;
using System.Security.Policy;
using System.Web;

namespace ShopApp.WebUI.Controllers;

public class ShopController : Controller
{
    private readonly IHttpClientFactory _httpClientFactory;
    public ShopController(IHttpClientFactory httpClientFactory)
    {
        this._httpClientFactory = httpClientFactory;
    }

    public async Task<IActionResult> List(string category, int page = 1)
    {
        var pageSize = 3;
        var httpClient = _httpClientFactory.CreateClient("api");
        var queryString = new Dictionary<string, string>
    {
        { "name", category },
        { "page", page.ToString() },
        { "pageSize", pageSize.ToString() }
    };

        using (var response = await httpClient.GetAsync(QueryHelpers.AddQueryString("Products/list", queryString)))
        {
            response.EnsureSuccessStatusCode();
            string apiResponse = await response.Content.ReadAsStringAsync();
            var products = JsonConvert.DeserializeObject<ProductListVm>(apiResponse);
            return View(products);
        }
    }

    public async Task<IActionResult> Details(string url)
    {
        var httpClient = _httpClientFactory.CreateClient("api");

        using (var response = await httpClient.GetAsync($"Products/details/{url}"))
        {
            if (response.IsSuccessStatusCode)
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                var product = JsonConvert.DeserializeObject<ProductVm>(apiResponse);

                if (product == null)
                {
                    return NotFound(); 
                }

                return View(product);
            }
            return NotFound();
           
        }

    }

    public async Task<IActionResult> Search(string q)
    {
        var httpClient = _httpClientFactory.CreateClient("api");

        using (var response = await httpClient.GetAsync($"Products/search/{q}"))
        {
            if (response.IsSuccessStatusCode)
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                var products = JsonConvert.DeserializeObject<List<ProductVm>>(apiResponse);

                if (products == null)
                {
                    return NotFound();
                }

                return View(products);
            }
            return NotFound();

        }

    }
}

ShopApp.WebUI/ViewComponents/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ShopApp.Business.Abstratc;
using ShopApp.Business.Models.VMs.CategoryVms;
using ShopApp.Business.Models.VMs.ProductVms;
using ShopApp.Entity.Entities;


namespace ShopApp.WebUI.ViewComponents
{
    public class CategoriesViewComponent:ViewComponent
    {

        private readonly HttpClient _httpClient;
        public CategoriesViewComponent(HttpClient httpClient)
        {
            this._httpClient = httpClient;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (RouteData.Values["category"] != null)
                ViewBag.SelectedCategory = RouteData?.Values["category"];
            var categories = new List<CategoryVm>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7207/api/category"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    categories = JsonConvert.DeserializeObject<List<CategoryVm>>(apiResponse);
                }
            }
            return View(categories);
            //return View(await _categoryServices.GetAll());
        }

    }
}

ShopApp.WebUI/Views/Shop/Details.cshtml
@model ProductVm


<div class="row">
    <div class="col-md-3">
        <img src="~/img/@Model.ImageUrl" class="img-fluid">
    </div>
    <div class="col-md-9">                
            <h1 class="mb-3">@Model.Name</h5> <hr>

            @foreach (var item in @Model.Categories)
            {
                <a asp-controller="shop" asp-action="list" asp-route-category="@item.Url" class="btn btn-link p-0 mb-3">@item.Name</a>
            }
            <div class="mb-3">
                <h4 class="text-primary mb-3">
                    <i class="fas fa-lira-sign"></i>@Model.Price
                </h4>
                
                <form asp-controller="Cart" asp-action="AddToCart" method="POST" class="form-inline">
                    <input type="hidden" name="productId" value="@Model.ProductId">
                    <div class="input-group mb-3">
                        <input type="number" name="quantity" class="form-control" value="1" min="1" step="1" style="width: 100px;">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-cart-plus"></i>Add to Cart                                
                            </button>
                        </div>
                    </div>     
               
                </form>
            </h6>
    </div>
</div>
<div class="row">
    <div class="col-md-12 p-5">
        <p class="p-3">@Html.Raw(Model.Description)</p>
    </div>
</div>

ShopApp.WebUI/Views/Shop/List.cshtml
@model ProductListVm
@{
    var products = Model.Products;
}


<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach (var product in @products)
            {
                <div class="col-md-4">
                    @await Html.PartialAsync("_product", product)
                </div>
            }
        </div>  <div class="row">
            <div class="col">
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                        @for (int i = 0; i < Model.PageInfo.TotalPages(); i++)
                        {
                            if (string.IsNullOrEmpty(Model.PageInfo.CurrentCategory))
                            {
                                <li class="page-item @(Model.PageInfo.CurrentPage == i + 1 ? "active" : "")"><a class="page-link" href="/products?page=@(i+1)">@(i + 1)</a></li>
                            }
                            else
                            {
                                <li class="page-item @(Model.PageInfo.CurrentPage == i + 1 ? "active" : "")"><a class="page-link @(Model.PageInfo.CurrentPage==i+1?"active":"")" href="/products/@Model.PageInfo.CurrentCategory?page=@(i+1)">@(i + 1)</a></li>
                            }
                        }
                        <li class="page-item"><a class="page-link" href="#">Next</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>

</div>

ShopApp.WebUI/Views/Shop/Search.cshtml
@model List<ProductVm>
@{
    var products = Model;
}


<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach (var product in @products)
            {
                <div class="col-md-4">
                    @await Html.PartialAsync("_product", product)
                </div>
            }
    </div>

</div>