ShopApp.WebUI/Areas/Admin/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ShopApp.Business.Abstratc;
using ShopApp.Business.Models.DTOs.ProductDtos;
using ShopApp.Business.Models.VMs;
using ShopApp.Business.Models.VMs.CategoryVms;
using ShopApp.Business.Models.VMs.ProductVms;
using ShopApp.Entity.Entities;
using ShopApp.WebUI.Extentions;
using System.Net.Http;
using System.Text;

namespace ShopApp.WebUI.Areas.Admin.Controllers;

[Area("Admin")]
public class ProductController : Controller
{
    private readonly IHttpClientFactory _httpClientFactory;
    public ProductController(IHttpClientFactory httpClientFactory)
    {
        this._httpClientFactory = httpClientFactory;
    }

    public async Task<IActionResult> ProductList()
    {
        var httpClient = _httpClientFactory.CreateClient("api");

        using (var response = await httpClient.GetAsync("Products"))
        {
            string apiResponse = await response.Content.ReadAsStringAsync();
            var products = JsonConvert.DeserializeObject<List<ProductVm>>(apiResponse);
            return View(products);
        }
    }

    public IActionResult ProductCreate()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> ProductCreate(ProductCreateDto model)
    {
        if (ModelState.IsValid)
        {
            var httpClient = _httpClientFactory.CreateClient("api");
            var jsonContent = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

            using (var response = await httpClient.PostAsync("Products", jsonContent))
            {
                if (response.IsSuccessStatusCode)
                {
                    //TempData.Put("message", new AlertMessage()
                    //{
                    //    Title = "Success",
                    //    Message = $"{model.Name} was added successfully",
                    //    AlertType = "success"
                    //});
                    return RedirectToAction("ProductList");
                }
                else
                {
                    //TempData.Put("message", new AlertMessage()
                    //{
                    //    Title = "Error",
                    //    Message = "There was an error adding the product",
                    //    AlertType = "danger"
                    //});
                }
            }
        }

        return View(model);
    }

    public async Task<IActionResult> ProductEdit(int id)
    {
        var httpClient = _httpClientFactory.CreateClient("api");
        var product = new ProductUpdateDto();

        using (var response = await httpClient.GetAsync($"Products/{id}"))
        {
            string apiResponse = await response.Content.ReadAsStringAsync();
            var productVm = JsonConvert.DeserializeObject<ProductVm>(apiResponse);
            product = new ProductUpdateDto()
            {
                ProductId = productVm.ProductId,
                Name = productVm.Name,
                Url = productVm.Url,
                Price = productVm.Price,
                Description = productVm.Description,
                ImageUrl = productVm.ImageUrl,
                IsApproved = productVm.IsApproved,
                IsHome = productVm.IsHome,
                SelectedCategories = productVm.Categories.Select(i => i.CategoryId).ToArray()
            };
        }

        using (var response = await httpClient.GetAsync("Category"))
        {
            string apiResponse = await response.Content.ReadAsStringAsync();
            var categories = JsonConvert.DeserializeObject<List<CategoryVm>>(apiResponse);

            ViewBag.Categories = categories;
        }


        return View(product);
    }


    [HttpPost]
    public async Task<IActionResult> ProductEdit(ProductUpdateDto model, int[] categoryIds, IFormFile file)
    {
        var httpClient = _httpClientFactory.CreateClient("api");

        // Dosya yükleme işlemi, eğer dosya sağlanmışsa
        if (file != null)
        {
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Img", file.FileName);
            using (var stream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }
            model.ImageUrl = file.FileName;
        }
        else
        {
            model.ImageUrl = "3.jpg"; // Varsayılan resim
        }

        // Kategorileri model'e ekle
        model.SelectedCategories = categoryIds.ToArray();

        // Ürünü güncelle
        var jsonContent = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");
        using (var response = await httpClient.PutAsync($"Products/{model.ProductId}", jsonContent))
        {
            if (response.IsSuccessStatusCode)
            {
                TempData.Put("message", new AlertMessage()
                {
                    Title = "Başarıyla güncellendi",
                    Message = $"{model.Name} başarıyla güncellendi",
                    AlertType = "success"
                });
                return RedirectToAction("ProductList");
            }
            else
            {
                TempData.Put("message", new AlertMessage()
                {
                    Title = "Hata",
                    Message = "Ürün güncellenirken bir hata oluştu",
                    AlertType = "danger"
                });
            }
        }

        // Eğer buraya geldiysek, bir şeyler yanlış gitti, formu yeniden göster
        var httpClientForCategories = _httpClientFactory.CreateClient("api");
        using (var response = await httpClientForCategories.GetAsync("Categories"))
        {
            string apiResponse = await response.Content.ReadAsStringAsync();
            var categories = JsonConvert.DeserializeObject<List<CategoryVm>>(apiResponse);
            ViewBag.Categories = categories;
        }

        return View(model);
    }



    public async Task<IActionResult> DeleteProduct(int productId)
    {
        var httpClient = _httpClientFactory.CreateClient("api");

        // Ürünü sil
        using (var response = await httpClient.DeleteAsync($"Products/{productId}"))
        {
            if (response.IsSuccessStatusCode)
            {
                TempData.Put("message", new AlertMessage()
                {
                    Title = "Başarıyla silindi",
                    Message = $"Ürün başarıyla silindi",
                    AlertType = "success"
                });
            }
            else
            {
                TempData.Put("message", new AlertMessage()
                {
                    Title = "Hata",
                    Message = "Ürün silinirken bir hata oluştu",
                    AlertType = "danger"
                });
            }
        }

        return RedirectToAction("ProductList");
    }

}

ShopApp.WebUI/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopApp.Business.Abstratc;
using ShopApp.DataAccess.Identity;
using ShopApp.WebUI.Areas.Admin.Models;
namespace ShopApp.WebUI.Areas.Admin.Controllers
{
        [Area("Admin")]
    public class RoleController : Controller
    {
        private RoleManager<IdentityRole> _roleManager;
        private UserManager<User> _userManager;
        public RoleController(
                                RoleManager<IdentityRole> roleManager,
                                UserManager<User> userManager
                                )
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public async Task<IActionResult> RoleEdit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            var members = new List<User>();
            var nonmembers = new List<User>();
            var users = await _userManager.Users.ToListAsync();
            foreach (var user in users)
            {
                var list = await _userManager.IsInRoleAsync(user, role.Name) ? members : nonmembers;
                list.Add(user);
            }
            var model = new RoleDetails()
            {
                Role = role,
                Members = members,
                NonMembers = nonmembers
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> RoleEdit(RoleEditModel model)
        {
            //if (ModelState.IsValid)
            //{
            foreach (var userId in model.IdsToAdd ?? new string[] { })
            {
                var user = await _userManager.FindByIdAsync(userId);
                if (user != null)
                {
                    var result = await _userManager.AddToRoleAsync(user, model.RoleName);
                    if (!result.Succeeded)
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                }
            }

            foreach (var userId in model.IdsToDelete ?? new string[] { })
            {
                var user = await _userManager.FindByIdAsync(userId);
                if (user != null)
                {
                    var result = await _userManager.RemoveFromRoleAsync(user, model.RoleName);
                    if (!result.Succeeded)
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                }
                //}
            }
            return Redirect("/admin/role/" + model.RoleId);
        }

        public IActionResult RoleList()
        {
            return View(_roleManager.Roles);
        }
        public IActionResult RoleCreate()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> RoleCreate(RoleModel model)
        {
            if (ModelState.IsValid)
            {
                var resul = await _roleManager.CreateAsync(new IdentityRole(model.Name));
                if (resul.Succeeded)
                {
                    return RedirectToAction("RoleList");
                }
                else
                {
                    foreach (var item in resul.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }
            return View(model);
        }

    }
}

ShopApp.WebUI/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShopApp.Business.Abstratc;
using ShopApp.Business.Models.VMs;
using ShopApp.Business.Models.VMs.IdentityVms;
using ShopApp.DataAccess.Identity;
using ShopApp.WebUI.Extentions;

namespace ShopApp.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {

        private RoleManager<IdentityRole> _roleManager;
        private UserManager<User> _userManager;
        public UserController(
                                RoleManager<IdentityRole> roleManager,
                                UserManager<User> userManager
                                )
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult UserList()
        {
            return View(_userManager.Users);
        }


        public async Task<IActionResult> UserEdit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                var selectedRoles = await _userManager.GetRolesAsync(user);
                var roles = _roleManager.Roles.Select(i => i.Name);
                ViewBag.Roles = roles;

                return View(new UserVm()
                {
                    UserId = user.Id,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    UserName = user.UserName,
                    Email = user.Email,
                    EmailConfirmed = user.EmailConfirmed,
                    SelectedRoles = selectedRoles
                });
            }
            TempData.Put("message", new AlertMessage()
            {
                Title = "User not found",
                Message = "User not found",
                AlertType = "danger"
            });
            return Redirect("~/");
        }

        [HttpPost]
        public async Task<IActionResult> UserEdit(UserVm model, string[] selectedRoles)
        {
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user != null)
            {
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.UserName = model.UserName;
                user.Email = model.Email;
                user.EmailConfirmed = model.EmailConfirmed;

                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    var userRoles = await _userManager.GetRolesAsync(user);
                    selectedRoles = selectedRoles ?? new string[] { };
                    result = await _userManager.AddToRolesAsync(user, selectedRoles.Except(userRoles).ToArray());
                    if (!result.Succeeded)
                    {
                        ModelState.AddModelError("", "Selected roles cannot be added");
                        return View(model);
                    }
                    result = await _userManager.RemoveFromRolesAsync(user, userRoles.Except(selectedRoles).ToArray());
                    if (!result.Succeeded)
                    {
                        ModelState.AddModelError("", "Selected roles cannot be removed");
                        return View(model);
                    }
                    TempData.Put("message", new AlertMessage()
                    {
                        Title = "User updated successfully",
                        Message = "User updated successfully",
                        AlertType = "success"
                    });
                    return RedirectToAction("UserList");
                }
            }
            return View(model);
        }

    }
}

ShopApp.WebUI/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopApp.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopApp.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_AdminNavbar"/>
    </header>

    <main role="main" class="pb-3">
        <div class="container mt-4 mb-3">
            <div class="row">
                <div class="col-md-12">
                    @if (TempData["message"] != null)
                    {
                        var message = TempData.Get<ShopApp.WebUI.Models.AlertMessage>("message");
                        if (message != null)
                        {
                            <partial name="_ResultMessages" model="message" />
                        }
                    }
                    @RenderBody()
                </div>
            </div>
        </div>
    </main>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ShopApp.WebUI - <a asp-area="Admin" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ShopApp.WebUI/Areas/Admin/Views/Shared/_AdminNavbar.cshtml
<nav class="navbar bg-primary navbar-dark navbar-expand-sm">
    <div class="container">
        <a href="/Admin" class="navbar-brand">
            ShopApp
        </a>
        <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Product" asp-action="productlist" class="nav-link">
                        Products
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Category" asp-action="categorylist" class="nav-link">
                        Categories
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Role" asp-action="RoleList" class="nav-link">
                        Role List
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="User" asp-action="UserList" class="nav-link">
                        User List
                    </a>
                </li>
           
        </ul>

        <ul class="navbar-nav ml-auto">
            
                <li class="nav-item">
                    <a asp-controller="account" asp-action="manage" class="nav-link">
                        @User.Identity.Name
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="account" asp-action="logout" class="nav-link">
                        Logout
                    </a>
                </li>
           

        </ul>





    </div>
</nav>

ShopApp.WebUI/Areas/Admin/Views/Shared/_ResultMessages.cshtml
@model AlertMessage

<div class="row">
    <div class="col-md-12">
        <div class="alert alert-@Model.AlertType">
            <h3 class="alert">
                @Model.Title
            </h3>
            <p>
                @Model.Message
            </p>
        </div>
    </div>
</div>